<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?=__('Qty') ?></span></label>	
            <script type="text/x-magento-init">    
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "qty_btns": {
                                "component": "DaveM_Test/js/view/product/view/qty_btns",
                                "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                            }
                        }
                    }
                }    
            }
            </script>
            <div class="control" data-bind="scope: 'qty_btns'">
                <button data-bind="click: decreaseQty">-</button>
                <input data-bind="value: qty()"
                       type="number"
                       name="qty"
                       id="qty"
                       value="<?=$block->getProductDefaultQty() * 1 ?>"
                       title="<?=__('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button data-bind="click: increaseQty">+</button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?=$buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?=$buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>